apiVersion: v1
kind: Service
metadata:
  name: csv-parser-service
spec:
  selector:
    app: csv-parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
