apiVersion: v1
kind: Service
metadata:
  name: sample-server-service
spec:
  selector:
    app: sample-server
  ports:
  - name: http-receiver # 任意のポート名
    protocol: TCP
    port: 8080
    targetPort: 8000
  type: ClusterIP